create table if not exists public.photos (
  id bigint generated by default as identity (start with 101 increment by 1) primary key,
  src text not null default '',
  click_count integer not null default 0,
  name text not null default '',
  uploader_account text not null default '',
  replaced_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('upload', 'replace', 'music')),
  account text not null default '',
  photo_id bigint,
  file_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values
  ('graduation-photos', 'graduation-photos', true),
  ('graduation-music', 'graduation-music', true)
on conflict (id) do update set public = excluded.public;

create or replace function public.is_graduation_account(account text)
returns boolean
language sql
immutable
as $$
  select account ~ '^[0-9]+$'
    and (
      account::bigint between 202324002001 and 202324002090
      or account::bigint between 202324001001 and 202324001050
    );
$$;

alter table public.photos enable row level security;
alter table public.activity_logs enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "photos are public readable" on public.photos;
create policy "photos are public readable"
on public.photos for select
to anon
using (true);

drop policy if exists "photos can be created by class accounts or view counters" on public.photos;
create policy "photos can be created by class accounts or view counters"
on public.photos for insert
to anon
with check (
  public.is_graduation_account(uploader_account)
  or public.is_graduation_account(replaced_by)
  or (id between 1 and 100 and src = '')
);

drop policy if exists "photos can be updated for counters and replacements" on public.photos;
create policy "photos can be updated for counters and replacements"
on public.photos for update
to anon
using (true)
with check (
  public.is_graduation_account(uploader_account)
  or public.is_graduation_account(replaced_by)
  or (id between 1 and 100 and src = '')
);

drop policy if exists "logs can be written by class accounts" on public.activity_logs;
create policy "logs can be written by class accounts"
on public.activity_logs for insert
to anon
with check (public.is_graduation_account(account));

drop policy if exists "logs are readable for site records panel" on public.activity_logs;
create policy "logs are readable for site records panel"
on public.activity_logs for select
to anon
using (true);

drop policy if exists "settings are public readable" on public.app_settings;
create policy "settings are public readable"
on public.app_settings for select
to anon
using (true);

drop policy if exists "music setting can be updated by site clients" on public.app_settings;
create policy "music setting can be updated by site clients"
on public.app_settings for insert
to anon
with check (key = 'music');

drop policy if exists "music setting can be replaced by site clients" on public.app_settings;
create policy "music setting can be replaced by site clients"
on public.app_settings for update
to anon
using (key = 'music')
with check (key = 'music');

drop policy if exists "photo files are public readable" on storage.objects;
create policy "photo files are public readable"
on storage.objects for select
to anon
using (bucket_id in ('graduation-photos', 'graduation-music'));

drop policy if exists "photo files can be uploaded" on storage.objects;
create policy "photo files can be uploaded"
on storage.objects for insert
to anon
with check (bucket_id in ('graduation-photos', 'graduation-music'));
